"""Compatibility alias for the older public ``edge_lstm.ir_graph`` namespace."""

from edge_lstm.ir import (
    DuplicateOperatorError,
    FPGACost,
    Graph,
    InvalidOperatorDefinitionError,
    InvalidOperatorInstanceError,
    Operator,
    OperatorError,
    OperatorRegistry,
    OperatorRegistryError,
    UnknownOperatorError,
    Value,
    ValueType,
    get_default_registry,
)
from edge_lstm.ir.validation import (
    GraphValidationError,
    IRValidationError,
    OperatorValidationError,
    TopologyValidationError,
    ValueValidationError,
    validate_fpga_constraints,
    validate_graph,
    validate_ir,
    validate_operators,
    validate_topology,
    validate_values,
)

__all__ = [
    "DuplicateOperatorError",
    "FPGACost",
    "Graph",
    "GraphValidationError",
    "IRValidationError",
    "InvalidOperatorDefinitionError",
    "InvalidOperatorInstanceError",
    "Operator",
    "OperatorError",
    "OperatorValidationError",
    "OperatorRegistry",
    "OperatorRegistryError",
    "TopologyValidationError",
    "UnknownOperatorError",
    "Value",
    "ValueValidationError",
    "ValueType",
    "get_default_registry",
    "validate_fpga_constraints",
    "validate_graph",
    "validate_ir",
    "validate_operators",
    "validate_topology",
    "validate_values",
]
